### ISSUE TITLE
建议：适配9.3.5.9版本

### ISSUE THREAD

**Issue by sbmatch** [zjns/QMHelper#3]
这是一个低内存占用，可dts 可使用原生媒体播放卡片的版本
app链接：https://android-apps.pp.cn/fs08/2019/08/30/3/110_ad6f4580d4f108922527347d515111c1.apk

**Comment by zjns** [comment]
DTS音效我觉得没啥用，也从来不用（~懒，不想花时间适配旧版本~）。
