### ISSUE TITLE
太极里面模块不能用。

### ISSUE THREAD

**Issue by mobeiCanyue** [zjns/QMHelper#4]
大佬能不能去登个账号，提交一下白名单，这样就可以在不root的情况下，使用您的这个模块了。

**Comment by zjns** [comment]
太极能用吗？

**Comment by mobeiCanyue** [comment]
> 太极能用吗？不知道支不支持加载so库

太极里只能加载它认为“安全”的模块，而“安全”需要它审核通过，加入白名单。
我昨天用了一下发现它说模块不可用（原因可能就是我说的那样）

**Comment by mobeiCanyue** [comment]
请问可以了吗

**Comment by zjns** [comment]
提交几天了，还在审核中，建议用LSposed或者LSPatch。

**Comment by muleos** [comment]
![Collage_20221021_220757](https://user-images.githubusercontent.com/33519597/197215712-7c12155c-3a6b-483f-bf12-ba798ee2953f.jpg)
开发者您好，我是太极无极用户，模块不需要添加白名单也可以使用。但是QMhelper在加载过程中只出现了这个弹窗，后续设置了找不到设置，进不去，能否解决一下呢，太极识别到加载了，但是找不到设置界面。还有一个用太极的原因，lspatch内置的，鸿蒙3.0最新系统已经开始闪退了，直接QQ音乐加载进不去。mate50机型，但太极仍可以使用。谢谢。

**Comment by zjns** [comment]
> ![Collage_20221021_220757](https://user-images.githubusercontent.com/33519597/197215712-7c12155c-3a6b-483f-bf12-ba798ee2953f.jpg) 开发者您好，我是太极无极用户，模块不需要添加白名单也可以使用。但是QMhelper在加载过程中只出现了这个弹窗，后续设置了找不到设置，进不去，能否解决一下呢，太极识别到加载了，但是找不到设置界面。还有一个用太极的原因，lspatch内置的，鸿蒙3.0最新系统已经开始闪退了，直接QQ音乐加载进不去。mate50机型，但太极仍可以使用。谢谢。

QQ音乐啥版本？请使用较新的客户端。

**Comment by muleos** [comment]
>11.10.1.8 应该是最新版了

**Comment by muleos** [comment]
在之前太极就是不显示的，就是更新以后，lsp内置闪退了，我用的微博助手，哔哩漫游 qa模块 小红书模块太极内置都没有问题，猜测应该是QA设置菜单的原因。我QQ音乐最新版64位的都不显示，都是首次进入会提示，后面找不到菜单界面。我可以帮忙测试太极，希望能解决。发自我的手机-------- 原始邮件 --------发件人： mobeiCanyue ***@***.***>日期： 2022年10月21日周五 半夜11:12收件人： zjns/QMHelper ***@***.***>抄送： muleos ***@***.***>, Comment ***@***.***>主    题： Re: [zjns/QMHelper] 太极里面模块不能用。 (Issue #4)





11.10.1.8 应该是最新版了





鸿蒙底层较改动较大，很多模块都会故障

**Comment by muleos** [comment]
> > > 11.10.1.8 应该是最新版了
> 
> 你的模块在太极里面是怎么生效的，为什么我的太极显示暂不支持 ![Screenshot_2022-10-21-23-07-28-349_me weishu exp](https://user-images.githubusercontent.com/81098819/197228439-2f8b68f4-1aba-4997-b39c-c17ff99331cf.jpg)

你这个是因为太极那边的问题，没申请过，但是我无极也应用不成功。

**Comment by zjns** [comment]
> 在之前太极就是不显示的，就是更新以后，lsp内置闪退了，我用的微博助手，哔哩漫游 qa模块 小红书模块太极内置都没有问题，猜测应该是QA设置菜单的原因。我QQ音乐最新版64位的都不显示，都是首次进入会提示，后面找不到菜单界面。我可以帮忙测试太极，希望能解决。发自我的手机-------- 原始邮件 --------发件人： mobeiCanyue ***@***.***>日期： 2022年10月21日周五 半夜11:12收件人： zjns/QMHelper ***@***.***>抄送： muleos ***@***.***>, Comment ***@***.***>主 题： Re: [zjns/QMHelper] 太极里面模块不能用。 (Issue #4) 11.10.1.8 应该是最新版了 鸿蒙底层较改动较大，很多模块都会故障 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

需要一枚无极码，已经在太极公众号下索要，还没得到回复。

**Comment by zjns** [comment]
已上架太极。

**Comment by mobeiCanyue** [comment]
万分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月2日(星期三) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjns/QMHelper] 太极里面模块不能用。 (Issue #4)





 
已上架太极。
